export default {
  login: "Itsvi-ctor",
  id: 89270483,
  node_id: "MDQ6VXNlcjg5MjcwNDgz",
  avatar_url: "https://avatars.githubusercontent.com/u/89270483?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Itsvi-ctor",
  html_url: "https://github.com/Itsvi-ctor",
  followers_url: "https://api.github.com/users/Itsvi-ctor/followers",
  following_url:
    "https://api.github.com/users/Itsvi-ctor/following{/other_user}",
  gists_url: "https://api.github.com/users/Itsvi-ctor/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Itsvi-ctor/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Itsvi-ctor/subscriptions",
  organizations_url: "https://api.github.com/users/Itsvi-ctor/orgs",
  repos_url: "https://api.github.com/users/Itsvi-ctor/repos",
  events_url: "https://api.github.com/users/Itsvi-ctor/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Itsvi-ctor/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "vicolaniyan.netlify.app",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: "itsvic_tor",
  public_repos: 9,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2021-08-20T17:07:22Z",
  updated_at: "2022-09-24T13:21:35Z",
};
